apiVersion: v1
kind: ConfigMap
metadata:
  name: my-trusted-ca-bundle
  namespace: my-namespace
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
  annotations:
    openshift.io/owning-component: Networking / cluster-network-operator
# START OMIT
data:
  ca-bundle.crt: |
    # Cluster CA certificates
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----

    # User-provided proxy CA certificates
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----

# END OMIT

