apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-operator-system

resources:
  - manager.yaml

configMapGenerator:
  - name: trusted-ca-bundle
    options:
      labels:
        config.openshift.io/inject-trusted-cabundle: "true"
