apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: controller:latest
          # START OMIT
          volumeMounts:
            - name: trusted-ca-bundle
              mountPath: /etc/pki/tls/certs
              readOnly: true
      # END OMIT
      # START VOLUMES OMIT
      volumes:
        - name: trusted-ca-bundle
          configMap:
            name: trusted-ca-bundle
            items:
              - key: ca-bundle.crt
                path: tls-ca-bundle.pem
# END VOLUMES OMIT

